<?php

namespace AppBundle\Repository;

/**
 * EntityEntityTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeEntityTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
