<?php

namespace AppBundle\Repository;

/**
 * EntityTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
