<?php

namespace AppBundle\Repository;

/**
 * EntityPropertyValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityPropertyValueRepository extends \Doctrine\ORM\EntityRepository
{
}
