<?php

namespace AppBundle\Repository;

/**
 * EntityPropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityPropertyRepository extends \Doctrine\ORM\EntityRepository
{
}
