<?php

namespace AppBundle\Repository;

/**
 * EntityTypePropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityTypePropertyRepository extends \Doctrine\ORM\EntityRepository
{
}
