<?php

namespace AppBundle\Repository;

/**
 * FranchiseeEntityTypePropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FranchiseeEntityTypePropertyRepository extends \Doctrine\ORM\EntityRepository
{
}
