<?php

namespace AppBundle\Repository;

/**
 * FranchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FranchRepository extends \Doctrine\ORM\EntityRepository
{
}
