<?php

namespace AppBundle\Repository;

/**
 * FranchEntityPropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FranchEntityPropertyRepository extends \Doctrine\ORM\EntityRepository
{
}
