<?php

namespace AppBundle\Repository;

/**
 * FranchiseeEntityPropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FranchiseeEntityPropertyRepository extends \Doctrine\ORM\EntityRepository
{
}
