<?php

namespace AppBundle\Repository;

/**
 * FranchiseeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FranchiseeRepository extends \Doctrine\ORM\EntityRepository
{
}
