# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'

    app.form.type.customProperty:
        class: AppBundle\Form\Type\CustomPropertyType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: custom_property_type }

    admin.franchisee:
        class: AppBundle\Admin\FranchiseeAdmin
        arguments: [~, AppBundle\Entity\Franchisee, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Франчайзи }
        public: true

    admin.property:
        class: AppBundle\Admin\PropertyAdmin
        arguments: [~, AppBundle\Entity\Property, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Свойства }
        public: true

    admin.entity.type:
        class: AppBundle\Admin\EntityTypeAdmin
        arguments: [~, AppBundle\Entity\EntityType, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Типы сущностей }
        public: true

    admin.property.type:
        class: AppBundle\Admin\PropertyTypeAdmin
        arguments: [~, AppBundle\Entity\PropertyType, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Типы свойств }
        public: true

    admin.employee:
        class: AppBundle\Admin\EmployeeAdmin
        arguments: [~, AppBundle\Entity\Employee, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Работники }
        public: true
